# Import Bibliotheken

In [35]:
import pandas as pd
import numpy as np

# Daten

## Datenimport

In [36]:
rawdata_df = pd.read_excel('data/raw/Google_Rezensionen.xlsx')
rawdata_df

,Tankstellenname,Datum,Bewertung,Kommentar,Kunde,Antwort,Kategorien
0,TS Wittstock,2022-09-30 17:31:00,4,NaN,Ricardo Franke,NaN,Null
1,TS Lengede,2022-09-30 14:53:24,5,Sehr nette Bedienung. Tolles Angebot. Sehr l...,Kat Eggi,"Hallo Kat Eggi, vielen Dank für Ihr tolles Fe...",Null
2,TS Südermarsch,2022-09-30 12:44:02,5,Beste Tankstelle im ganzem Umkreis! Riesige Bi...,Sam Michelsen,??,Null
3,TS Südermarsch,2022-09-30 07:45:06,5,NaN,Arne Bg,NaN,Null
4,TS Schleswig MC,2022-09-30 06:46:42,5,"Super nettes Personal, gutes Frühstück mit gro...",Sebastian Johannsen,NaN,"Personal, Shop, Bistro"
...,...,...,...,...,...,...,...
11077,TS Jübek,2014-07-16 07:08:37,5,"Sehr gut. Günstig , guter shop und einige and...",Jens Schmidt,NaN,"Pricing, Shop, Kraftstoffauswahl, Waschanlage,..."
11078,TS Sörup,2014-02-07 21:18:05,5,NaN,Uschi Hinrichsen,NaN,Null
11079,TS Neustadt am Rüb.,2013-09-21 15:26:28,5,Öffnungszeiten: Mo-So: 06:00 - 22:00 Uhr,Adrian Winkelmann,NaN,Öffnungszeiten
11080,TS Handewitt(SP),2012-11-05 11:16:00,5,"genug platz fuer wohnwagen, rechts beim autog...",Stan van de Kerkhof,NaN,"Personal, Kraftstoffauswahl"
11081,TS Handewitt(SP),2011-07-26 17:42:28,4,Ideal um kurz vor Dänemark nochmal Günstig zu...,Kevin Quiatkowski,NaN,Pricing

## Dateninformationen

In [37]:
rawdata_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11082 entries, 0 to 11081
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Tankstellenname  11082 non-null  object
 1   Datum            11082 non-null  datetime64[ns]
 2   Bewertung        11082 non-null  int64
 3   Kommentar        5136 non-null   object
 4   Kunde            11082 non-null  object
 5   Antwort          2622 non-null   object
 6   Kategorien       11082 non-null  object
dtypes: datetime64[ns](1), int64(1), object(5)
memory usage: 606.2+ KB

In [38]:
rawdata_df.describe()

          Bewertung
count  11082.000000
mean       4.272243
std        1.055864
min        1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000

## Datenaufbereitung

### Entfernung Spalte Antwort

In [39]:
data_df = rawdata_df.drop('Antwort',axis=1)
data_df

,Tankstellenname,Datum,Bewertung,Kommentar,Kunde,Kategorien
0,TS Wittstock,2022-09-30 17:31:00,4,NaN,Ricardo Franke,Null
1,TS Lengede,2022-09-30 14:53:24,5,Sehr nette Bedienung. Tolles Angebot. Sehr l...,Kat Eggi,Null
2,TS Südermarsch,2022-09-30 12:44:02,5,Beste Tankstelle im ganzem Umkreis! Riesige Bi...,Sam Michelsen,Null
3,TS Südermarsch,2022-09-30 07:45:06,5,NaN,Arne Bg,Null
4,TS Schleswig MC,2022-09-30 06:46:42,5,"Super nettes Personal, gutes Frühstück mit gro...",Sebastian Johannsen,"Personal, Shop, Bistro"
...,...,...,...,...,...,...
11077,TS Jübek,2014-07-16 07:08:37,5,"Sehr gut. Günstig , guter shop und einige and...",Jens Schmidt,"Pricing, Shop, Kraftstoffauswahl, Waschanlage,..."
11078,TS Sörup,2014-02-07 21:18:05,5,NaN,Uschi Hinrichsen,Null
11079,TS Neustadt am Rüb.,2013-09-21 15:26:28,5,Öffnungszeiten: Mo-So: 06:00 - 22:00 Uhr,Adrian Winkelmann,Öffnungszeiten
11080,TS Handewitt(SP),2012-11-05 11:16:00,5,"genug platz fuer wohnwagen, rechts beim autog...",Stan van de Kerkhof,"Personal, Kraftstoffauswahl"
11081,TS Handewitt(SP),2011-07-26 17:42:28,4,Ideal um kurz vor Dänemark nochmal Günstig zu...,Kevin Quiatkowski,Pricing

### Entfernung Null-Values

In [40]:
data_df = data_df.dropna()

In [41]:
data_df = data_df.drop_duplicates()

In [42]:
data_df

,Tankstellenname,Datum,Bewertung,Kommentar,Kunde,Kategorien
1,TS Lengede,2022-09-30 14:53:24,5,Sehr nette Bedienung. Tolles Angebot. Sehr l...,Kat Eggi,Null
2,TS Südermarsch,2022-09-30 12:44:02,5,Beste Tankstelle im ganzem Umkreis! Riesige Bi...,Sam Michelsen,Null
4,TS Schleswig MC,2022-09-30 06:46:42,5,"Super nettes Personal, gutes Frühstück mit gro...",Sebastian Johannsen,"Personal, Shop, Bistro"
5,TS Prisdorf,2022-09-29 17:22:44,5,Sehr höfliche Bedienstete! (Translated by Goo...,unbekannt,Personal
6,TS Wanderup,2022-09-29 15:38:02,5,"Immer gerne dort,nettes und zuvorkommendes Per...",Mona Johannsen,"Personal, Waschanlage"
...,...,...,...,...,...,...
11072,TS Jübek,2015-04-07 17:45:02,5,Dies ist einfach die beste tankstelle die ich...,Jens Schmidt,"Kraftstoffauswahl, Waschanlage"
11077,TS Jübek,2014-07-16 07:08:37,5,"Sehr gut. Günstig , guter shop und einige and...",Jens Schmidt,"Pricing, Shop, Kraftstoffauswahl, Waschanlage,..."
11079,TS Neustadt am Rüb.,2013-09-21 15:26:28,5,Öffnungszeiten: Mo-So: 06:00 - 22:00 Uhr,Adrian Winkelmann,Öffnungszeiten
11080,TS Handewitt(SP),2012-11-05 11:16:00,5,"genug platz fuer wohnwagen, rechts beim autog...",Stan van de Kerkhof,"Personal, Kraftstoffauswahl"
11081,TS Handewitt(SP),2011-07-26 17:42:28,4,Ideal um kurz vor Dänemark nochmal Günstig zu...,Kevin Quiatkowski,Pricing

In [43]:
data_df = data_df[data_df['Kategorien'].str.contains('Null')==False]
data_df

,Tankstellenname,Datum,Bewertung,Kommentar,Kunde,Kategorien
4,TS Schleswig MC,2022-09-30 06:46:42,5,"Super nettes Personal, gutes Frühstück mit gro...",Sebastian Johannsen,"Personal, Shop, Bistro"
5,TS Prisdorf,2022-09-29 17:22:44,5,Sehr höfliche Bedienstete! (Translated by Goo...,unbekannt,Personal
6,TS Wanderup,2022-09-29 15:38:02,5,"Immer gerne dort,nettes und zuvorkommendes Per...",Mona Johannsen,"Personal, Waschanlage"
10,TS Handewitt,2022-09-28 17:05:28,5,"Nettes, freundliches Personal (Translated by ...",Sabine Clausen,Personal
12,TS Bremen,2022-09-28 04:24:34,4,"Normale Tankstelle, die aber in der Tank-App n...",WATCH,"Pricing, Digital Fueling"
...,...,...,...,...,...,...
11072,TS Jübek,2015-04-07 17:45:02,5,Dies ist einfach die beste tankstelle die ich...,Jens Schmidt,"Kraftstoffauswahl, Waschanlage"
11077,TS Jübek,2014-07-16 07:08:37,5,"Sehr gut. Günstig , guter shop und einige and...",Jens Schmidt,"Pricing, Shop, Kraftstoffauswahl, Waschanlage,..."
11079,TS Neustadt am Rüb.,2013-09-21 15:26:28,5,Öffnungszeiten: Mo-So: 06:00 - 22:00 Uhr,Adrian Winkelmann,Öffnungszeiten
11080,TS Handewitt(SP),2012-11-05 11:16:00,5,"genug platz fuer wohnwagen, rechts beim autog...",Stan van de Kerkhof,"Personal, Kraftstoffauswahl"
11081,TS Handewitt(SP),2011-07-26 17:42:28,4,Ideal um kurz vor Dänemark nochmal Günstig zu...,Kevin Quiatkowski,Pricing

### Entfernung Sonderzeichen in Kommentaren

In [44]:
df_kommentar = data_df['Kommentar'].str.replace('\W', ' ', regex=True)
data_df.Kommentar = df_kommentar
#data_df.to_excel("C:/Users/loedu/Documents/test.xlsx")
data_df

C:\Users\flori\AppData\Local\Temp\ipykernel_23892\3079588843.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df.Kommentar = df_kommentar

,Tankstellenname,Datum,Bewertung,Kommentar,Kunde,Kategorien
4,TS Schleswig MC,2022-09-30 06:46:42,5,Super nettes Personal gutes Frühstück mit gro...,Sebastian Johannsen,"Personal, Shop, Bistro"
5,TS Prisdorf,2022-09-29 17:22:44,5,Sehr höfliche Bedienstete Translated by Goo...,unbekannt,Personal
6,TS Wanderup,2022-09-29 15:38:02,5,Immer gerne dort nettes und zuvorkommendes Per...,Mona Johannsen,"Personal, Waschanlage"
10,TS Handewitt,2022-09-28 17:05:28,5,Nettes freundliches Personal Translated by ...,Sabine Clausen,Personal
12,TS Bremen,2022-09-28 04:24:34,4,Normale Tankstelle die aber in der Tank App n...,WATCH,"Pricing, Digital Fueling"
...,...,...,...,...,...,...
11072,TS Jübek,2015-04-07 17:45:02,5,Dies ist einfach die beste tankstelle die ich...,Jens Schmidt,"Kraftstoffauswahl, Waschanlage"
11077,TS Jübek,2014-07-16 07:08:37,5,Sehr gut Günstig guter shop und einige and...,Jens Schmidt,"Pricing, Shop, Kraftstoffauswahl, Waschanlage,..."
11079,TS Neustadt am Rüb.,2013-09-21 15:26:28,5,Öffnungszeiten Mo So 06 00 22 00 Uhr,Adrian Winkelmann,Öffnungszeiten
11080,TS Handewitt(SP),2012-11-05 11:16:00,5,genug platz fuer wohnwagen rechts beim autog...,Stan van de Kerkhof,"Personal, Kraftstoffauswahl"
11081,TS Handewitt(SP),2011-07-26 17:42:28,4,Ideal um kurz vor Dänemark nochmal Günstig zu...,Kevin Quiatkowski,Pricing

In [45]:
data_without_spaces = data_df.replace(' +', ' ', regex=True)
data_without_spaces.Kommentar = data_without_spaces.Kommentar.str.lstrip()
data_without_spaces

,Tankstellenname,Datum,Bewertung,Kommentar,Kunde,Kategorien
4,TS Schleswig MC,2022-09-30 06:46:42,5,Super nettes Personal gutes Frühstück mit groß...,Sebastian Johannsen,"Personal, Shop, Bistro"
5,TS Prisdorf,2022-09-29 17:22:44,5,Sehr höfliche Bedienstete Translated by Google...,unbekannt,Personal
6,TS Wanderup,2022-09-29 15:38:02,5,Immer gerne dort nettes und zuvorkommendes Per...,Mona Johannsen,"Personal, Waschanlage"
10,TS Handewitt,2022-09-28 17:05:28,5,Nettes freundliches Personal Translated by Goo...,Sabine Clausen,Personal
12,TS Bremen,2022-09-28 04:24:34,4,Normale Tankstelle die aber in der Tank App ni...,WATCH,"Pricing, Digital Fueling"
...,...,...,...,...,...,...
11072,TS Jübek,2015-04-07 17:45:02,5,Dies ist einfach die beste tankstelle die ich ...,Jens Schmidt,"Kraftstoffauswahl, Waschanlage"
11077,TS Jübek,2014-07-16 07:08:37,5,Sehr gut Günstig guter shop und einige andere ...,Jens Schmidt,"Pricing, Shop, Kraftstoffauswahl, Waschanlage,..."
11079,TS Neustadt am Rüb.,2013-09-21 15:26:28,5,Öffnungszeiten Mo So 06 00 22 00 Uhr,Adrian Winkelmann,Öffnungszeiten
11080,TS Handewitt(SP),2012-11-05 11:16:00,5,genug platz fuer wohnwagen rechts beim autogas...,Stan van de Kerkhof,"Personal, Kraftstoffauswahl"
11081,TS Handewitt(SP),2011-07-26 17:42:28,4,Ideal um kurz vor Dänemark nochmal Günstig zu ...,Kevin Quiatkowski,Pricing

### Entfernung leere Kommentare

In [46]:
cleandata_df = data_without_spaces.query("Kommentar != '' ")
cleandata_df

# cleandata_df.to_excel("C:/Users/flori/Documents/test4.xlsx")

,Tankstellenname,Datum,Bewertung,Kommentar,Kunde,Kategorien
4,TS Schleswig MC,2022-09-30 06:46:42,5,Super nettes Personal gutes Frühstück mit groß...,Sebastian Johannsen,"Personal, Shop, Bistro"
5,TS Prisdorf,2022-09-29 17:22:44,5,Sehr höfliche Bedienstete Translated by Google...,unbekannt,Personal
6,TS Wanderup,2022-09-29 15:38:02,5,Immer gerne dort nettes und zuvorkommendes Per...,Mona Johannsen,"Personal, Waschanlage"
10,TS Handewitt,2022-09-28 17:05:28,5,Nettes freundliches Personal Translated by Goo...,Sabine Clausen,Personal
12,TS Bremen,2022-09-28 04:24:34,4,Normale Tankstelle die aber in der Tank App ni...,WATCH,"Pricing, Digital Fueling"
...,...,...,...,...,...,...
11072,TS Jübek,2015-04-07 17:45:02,5,Dies ist einfach die beste tankstelle die ich ...,Jens Schmidt,"Kraftstoffauswahl, Waschanlage"
11077,TS Jübek,2014-07-16 07:08:37,5,Sehr gut Günstig guter shop und einige andere ...,Jens Schmidt,"Pricing, Shop, Kraftstoffauswahl, Waschanlage,..."
11079,TS Neustadt am Rüb.,2013-09-21 15:26:28,5,Öffnungszeiten Mo So 06 00 22 00 Uhr,Adrian Winkelmann,Öffnungszeiten
11080,TS Handewitt(SP),2012-11-05 11:16:00,5,genug platz fuer wohnwagen rechts beim autogas...,Stan van de Kerkhof,"Personal, Kraftstoffauswahl"
11081,TS Handewitt(SP),2011-07-26 17:42:28,4,Ideal um kurz vor Dänemark nochmal Günstig zu ...,Kevin Quiatkowski,Pricing

In [47]:
cleandata_df['Kommentar'] = cleandata_df['Kommentar'].str.lower()

In [48]:
# Englische ÜBersetzung löschen
cleandata_df['Kommentar'] = cleandata_df['Kommentar'].str.split('translated by google').str[0]

In [49]:
cleandata_df.Kategorien = cleandata_df.Kategorien.str.replace(' ', '')

### Entfernung Spalte Kunde

In [50]:
cleandata_df = cleandata_df.drop('Kunde',axis=1)
cleandata_df

,Tankstellenname,Datum,Bewertung,Kommentar,Kategorien
4,TS Schleswig MC,2022-09-30 06:46:42,5,super nettes personal gutes frühstück mit groß...,"Personal,Shop,Bistro"
5,TS Prisdorf,2022-09-29 17:22:44,5,sehr höfliche bedienstete,Personal
6,TS Wanderup,2022-09-29 15:38:02,5,immer gerne dort nettes und zuvorkommendes per...,"Personal,Waschanlage"
10,TS Handewitt,2022-09-28 17:05:28,5,nettes freundliches personal,Personal
12,TS Bremen,2022-09-28 04:24:34,4,normale tankstelle die aber in der tank app ni...,"Pricing,DigitalFueling"
...,...,...,...,...,...
11072,TS Jübek,2015-04-07 17:45:02,5,dies ist einfach die beste tankstelle die ich ...,"Kraftstoffauswahl,Waschanlage"
11077,TS Jübek,2014-07-16 07:08:37,5,sehr gut günstig guter shop und einige andere ...,"Pricing,Shop,Kraftstoffauswahl,Waschanlage,Sta..."
11079,TS Neustadt am Rüb.,2013-09-21 15:26:28,5,öffnungszeiten mo so 06 00 22 00 uhr,Öffnungszeiten
11080,TS Handewitt(SP),2012-11-05 11:16:00,5,genug platz fuer wohnwagen rechts beim autogas...,"Personal,Kraftstoffauswahl"
11081,TS Handewitt(SP),2011-07-26 17:42:28,4,ideal um kurz vor dänemark nochmal günstig zu ...,Pricing

### Export bereinigter Datensatz

In [51]:
cleandata_df.to_excel('data/clean/Google_Rezensionen.xlsx')